#config_version=6

switches:
  s_left_flipper:
    number:
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper
  s_trough_1:
    number:
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
    number: